// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJ4rsM3TyiJtODzhmxvFpmBK1BT7kjz4',
    appId: '1:1045221478592:web:51d59e59b3cba2e70c5d25',
    messagingSenderId: '1045221478592',
    projectId: 'testenascermais',
    authDomain: 'testenascermais.firebaseapp.com',
    storageBucket: 'testenascermais.firebasestorage.app',
    measurementId: 'G-FM65RPMRTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzPIh9OsEVXioDfpu5AEHN6xbsJfZjWM',
    appId: '1:1045221478592:android:c938341ae4e71e780c5d25',
    messagingSenderId: '1045221478592',
    projectId: 'testenascermais',
    storageBucket: 'testenascermais.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPJ4rsM3TyiJtODzhmxvFpmBK1BT7kjz4',
    appId: '1:1045221478592:web:a5180c7b60830c390c5d25',
    messagingSenderId: '1045221478592',
    projectId: 'testenascermais',
    authDomain: 'testenascermais.firebaseapp.com',
    storageBucket: 'testenascermais.firebasestorage.app',
    measurementId: 'G-KTK8S9KFBH',
  );
}
