name: nascer_mais
description: Um aplicativo que estou desenvolvendo para facilitar o dia a dia dos profissionais da obstetrícia.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Utilidades e Formatação
  intl: ^0.20.2
  cupertino_icons: ^1.0.2

  # Persistência de Dados (Banco de Dados)
  sqflite: ^2.3.0               # Nativo (Android/iOS)
  sqflite_common_ffi: ^2.3.0+2  # Desktop/Testes
  sqflite_common_ffi_web: ^1.1.1 # Web (Vercel)
  path: ^1.9.0                  # Manipulação de caminhos

  # Câmera e Galeria de Fotos
  image_picker: ^1.1.0          # Selecionar foto
  image_cropper: ^11.0.0        # Editar/Cortar foto

  # Comunicação e Links
  url_launcher: ^6.2.5          # Abrir e-mail/links externos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

# Configuração dos Ícones do App
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "web/Nascermaisicon.PNG"

flutter:
  uses-material-design: true

  # Caso precise adicionar imagens fixas no futuro, use a seção assets abaixo:
  # assets:
  #   - assets/images/